services:
  mongodb:
    image: mongo:6.0 # Using a specific version is often more stable than 'latest'
    container_name: workproof_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - workproof_network
    restart: on-failure

  app:
    build: .
    container_name: workproof_app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    ports:
      - "6080:6080"
    volumes:
      - ./screenshots:/app/screenshots
      - ./reports:/app/reports
      - ./storage:/app/storage
    networks:
      - workproof_network
    restart: unless-stopped

networks:
  workproof_network:
    driver: bridge

volumes:
  mongodb_data:
