version: "3.12"
services:
  workproof-final:
    build: .
    image: workproof-final:latest
    container_name: workproof-final
    ports:
      - "8000:8000"
    environment:
      - OCR_ENGINE=paddle
